### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-validator#105]
It would be good to keep a changelog (https://keepachangelog.com/en/1.1.0/).

I like [scriv](https://scriv.readthedocs.io/en/latest/) to encourage notifying about meaningful changes instead of dumping PR titles (which I definitely do in many projects), which can sometimes be more or less than one-per-PR.

**Comment by Remi-Gau** [comment]
definitely more in favor of something a bit more curated
