### ISSUE TITLE
slimmed docker without web dependencies

### ISSUE THREAD

**Issue by bpinsard** [bids-standard/bids-validator#122]
Hi, 
_warning: I don't know anything about nodejs_

I noted that the bids-validator docker image is quite large for a tool that I personally use only on the command line, but even more frequently in github/gitlab actions where size matters if you want to run that on every change to a continuously created BIDS dataset. 

Digging into the layers (with dive), the npm install of the bids-validator generate a 971MB layer and some of the heaviest packages installed seems to be for the web interface (eg. next).
Not sure, but some of the space seems also used in a npm cache folder.
![Image](https://github.com/user-attachments/assets/78c26915-6417-4bdc-8cd8-3ecc65c7cf19)

I was wondering if there exists docker images without these dependencies, or a way to install the bids-validator with minimal dependency for command-line usage only so that I can create a lighter docker image.

Thanks!

**Comment by Remi-Gau** [comment]
I think this is for the legacy validator, no?

**Comment by Remi-Gau** [comment]
the bids validator base image used for building bids apps is already smaller and has clearly not been optmized to be small: https://hub.docker.com/r/bids/base_validator/tags

**Comment by Remi-Gau** [comment]
long answer: here is the blog post

https://bids-website.readthedocs.io/en/latest/blog/2024/11/13/bids-validator-2.html

short answer: the validator container does not yet contain the deno one AFDAICT

**Comment by Remi-Gau** [comment]
Just ran `docker build .` on main here https://github.com/bids-apps/base_validator
and it worked.

**Comment by bpinsard** [comment]
Thanks for all these infos, I clearly missed these important news :) 

I tried building the one here https://github.com/bids-standard/bids-validator but will try the base one.
I guess that will likely be a lighter image, so closing now.

**Comment by bpinsard** [comment]
base_validator docker build works, made an alternative from deno:alpine to further strip 30%. 

```
FROM denoland/deno:alpine-2.1.1
RUN deno install -Agf -n bids-validator jsr:@bids/validator@1.15.0
```

**Comment by Remi-Gau** [comment]
I should probably document this in the README of the base validator image for bids apps, no?
