### ISSUE TITLE
Validation regression

### ISSUE THREAD

**Issue by marcelzwiers** [bids-standard/bids-validator#2113]
If I use Pypi version `1.14.6` I get

```python
bids_validator.BIDSValidator().is_bids('/sub-01/func/sub-01_echo-1_sbref.json')
Out[18]: False
```
If I use Pypi version `1.14.7` I get

```python
bids_validator.BIDSValidator().is_bids('/sub-01/func/sub-01_echo-1_sbref.json')
Out[19]: True
```

I think `v1.14.6` is the correct result, because indeed the `task` entity is missing

**Comment by effigies** [comment]
JSON files are sidecars, so may have missing entities. It might not be terribly useful, but I don't see anything wrong with that.

**Comment by marcelzwiers** [comment]
I guess this is another side-effect of the inheritance principle :-(

**Comment by effigies** [comment]
I'd go so far as to call it the main effect of the inheritance principle. :-) 

If the sidecar can be found via the inheritance principle, it is valid. Previously, this was enforced by hand-written regular expressions, which were not always exhaustive. Now the matching is procedural.

**Comment by marcelzwiers** [comment]
This causes quite a lot of difficulties for me, is there a way I can still do the old-style strict validation on the json files?
