### ISSUE TITLE
Validation generates a message about needing to "trust this site"

### ISSUE THREAD

**Issue by arokem** [bids-standard/bids-validator#45]
The validator website includes the message that "Note: Selecting a dataset only performs validation. Files are never uploaded." 

However, when data is selected for upload the browser counters with something like this (Chrome): 

<img width="1392" alt="Screen Shot 2021-12-14 at 9 29 06 AM" src="https://user-images.githubusercontent.com/118582/146050883-e84b200d-72f0-49d9-8a30-1efed0b5916b.png">

Or like this (Firefox): 
<img width="1170" alt="Screenshot 2021-12-14 at 18 35 39" src="https://user-images.githubusercontent.com/118582/146050980-0e7e7f36-a90c-4ebd-852e-a554f06d0797.png">

As noted by @robertoostenveld, this is not in the validator code-base, but comes from the browser itself. The question is whether there is any way to prevent the browser from raising this, or some other way to mitigate this.

**Comment by effigies** [comment]
Nothing to do here, but this is being discussed in #88, so I'll plan to close this with that merge unless someone disagrees.
