### ISSUE TITLE
MAINT: post migration clean up

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-validator#52]
suggestions: 
- [ ] convert zenodo.json to citation.cff (do we plan to keep pushing the release to zeonodo?)
- [ ] contributors: I would be in favor of centralizing the listing of contributors in the spec repo so we could get rid of the all_contributors file
- [x] contributing: I can add a file that at least starts point to the general instructions we have on the bids website
- [ ] code climate config contains some lines about the python validator

thoughts?

**Comment by effigies** [comment]
* CITATION.cff: +1
* allcontributors hasn't been actively updated. Either enable the bot or get rid of it, IMO.
* contributing: https://github.com/bids-standard/bids-validator/blob/main/.github/CONTRIBUTING.md
* We don't use code climate. Let's just get rid of it.

**Comment by Remi-Gau** [comment]
okidoki
will take care of those to get some things of your plate
