### ISSUE TITLE
BIDS support policy and branching

### ISSUE THREAD

**Issue by effigies** [bids-standard/bids-validator#85]
The BIDS specification, schema and validator lifecycles are currently mixed. The schema is updated linearly with main, and there is no method to maintain a branch of the schema that fixes issues with the schema for the stable release without also including new features in the `main` branch.

As the validator is now heavily reliant on the schema, there is no difference to the validator between an update that fixes a bug in the schema and one that introduces a feature, which could potentially be changed or reverted before the next release of BIDS.

Here I propose a parallel branching strategy for the specification and the validator

Legend:

* main: `bids-specification:main`
* maint/1.10.0: `bids-specification:maint/1.10.0`
* validator-main: `bids-validator:main` (or `bids-validator:maint/1.15.x`)
* validator-dev: `bids-validator:dev`

```mermaid
---
config:
  gitGraph:
    parallelCommits: false
---
gitGraph TB:
  branch validator-main order: 2
  commit id: "v1.15.0.devN"
  checkout main
  commit tag: "v1.10.0" id: "schema-0.11.3"
  branch maint/1.10.0 order: 1
  checkout validator-main
  merge main tag: "v1.15.0"
  branch validator-dev order: 3
  checkout main
  commit id: "schema-0.11.4.dev1"
  checkout validator-dev
  merge main id: "v1.16.0.dev1"
  checkout main
  commit id: "schema-0.11.4.dev2"
  checkout validator-dev
  merge main id: "v1.16.0.dev2"
  checkout main
  checkout maint/1.10.0
  commit id: "schema-0.11.3.post1"
  checkout validator-main
  merge maint/1.10.0 tag: "v1.15.1"
  checkout main
  merge maint/1.10.0 id: "schema-0.11.4.dev3"
  checkout validator-dev
  merge main id: "v1.16.0.dev3"
  checkout main
  commit id: "schema-0.11.4.dev4"
  checkout validator-dev
  merge main id: "v1.16.0.dev4"
  checkout main
  commit id: "schema-0.11.4.dev5"
  checkout validator-dev
  merge main id: "v1.16.0.dev5"
  checkout maint/1.10.0
  commit id: "schema-0.11.3.post2" tag: "v1.10.0.post1"
  checkout validator-main
  merge maint/1.10.0 tag: "v1.15.2"
  checkout main
  merge maint/1.10.0 id: "schema-0.11.4.dev6"
```

By using `.postN` releases for fixes to the schema and `.devN` releases for new changes, the stable validator could follow the latest `.post` and the development version could follow the latest `.dev`.

I also include a `v1.10.0.post1` tag, which could be used for schema fixes that have rendering consequences, or things like fixing typos in the spec.

I will separately post a proposal for simultaneously publish stable and dev versions of the web validator.

**Comment by effigies** [comment]
Note that the "merges" between the specification and validator branches are not actual git merges. They would be the validator updating pins to versions of the schema pushed to https://jsr.io/@bids/schema/versions.

I have also posted this to https://github.com/bids-standard/bids-specification/issues/1977, for discussion of the mechanics of this model in the specification. This issue can focus more on the mechanics of the validator branching model and keeping synced using upstream schema versioning.

**Comment by effigies** [comment]
Also note that the matching of validator `v1.15.0` and spec `v1.10.0` is anachronistic and just an example. I do think we should aim to start using the patch releases only for fixes and not new features. And I think we should start pushing dev builds to JSR.

**Comment by Remi-Gau** [comment]
Quick clarification: we agree that we would only have a maint branch of the latest spec release, right ?
We don't intend of fixing bugs separately for 1.10 once 1.11 is out? Not even sure this would make sense actually.

**Comment by effigies** [comment]
Yes, absolutely, one maintenance and one development branch. As soon as there's a new release, everything ratchets forward.

Minor modification, though, we would be maintaining for 1.10.0, not 1.10. The next version is 1.10.1, unless a new BEP (or sufficiently large change) causes us to call it 1.11.0. Once 1.10.1 is released, our maintenance branch would be on 1.10.1.

I think in most cases, there would be only schema updates to the maintenance branches, so there would be no user-facing changes. However, if there are impacts on rendering, we could re-release the maintenance branch as `1.10.0.post1`, and the implication of such a version would be that there are no additions or semantic changes to the spec. From the perspective of a `BIDSVersion`, it is still `1.10.0`.

**Comment by effigies** [comment]
We have now had a schema-0.11.3.post1 release off of the `maint/1.10.0` branch in the spec, which pushed to https://pypi.org/project/bidsschematools/0.11.3.post1/#history and https://jsr.io/@bids/schema@0.11.3+1

![Image](https://github.com/user-attachments/assets/5da9d0cc-2620-4336-94e6-dfe43ab6d89f)

I believe the infrastructure needed in the spec repository is complete. The validator will now need a maintenance branch to track the stable releases.

**Comment by effigies** [comment]
![Image](https://github.com/user-attachments/assets/4297af10-27ca-420b-871f-47e7f6778b3f)

https://github.com/bids-standard/bids-validator/tree/stable is now pinned to https://jsr.io/@bids/schema@0.11.3+1

As I think about this more, I think instead of `stable`/`main`, we want `main`/`dev`. I think we want to default to merging into `main` unless there's a specific reason that it would produce an incompatibility with the latest spec release. Then `dev` would just regularly merge `main` and bump its `@bids/schema` pin to the latest `dev` release.
